name: 'ga4_warehouse'
version: '1.0.0'
config-version: 2

profile: 'ga4_warehouse'

# File paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Global variables for GA4 project
vars:
  # Define your GA4 dataset and project details
  ga4_export_dataset: 'analytics_123456789'  # Replace with your GA4 export dataset
  ga4_project: 'your-gcp-project'  # Replace with your GCP project
  
  # Date variables for incremental loads
  start_date: '2024-01-01'
  
  # Event exclusions (common internal/test events to filter)
  excluded_events: ['session_start', 'first_visit', 'scroll']

# Model configurations following best practices
models:
  ga4_warehouse:
    # Global model configs
    +persist_docs:
      relation: true
      columns: true
    
    # Staging layer - raw data cleaned and typed
    staging:
      +materialized: view
      +schema: staging
      ga4:
        +tags: ['staging', 'ga4']
        +docs:
          node_color: '#90EE90'  # Light green for staging
    
    # Intermediate layer - business logic transformations
    intermediate:
      +materialized: ephemeral  # Don't persist intermediate calculations
      +schema: intermediate
      ga4:
        +tags: ['intermediate', 'ga4']
        +docs:
          node_color: '#FFD700'  # Gold for intermediate
    
    # Marts layer - final analytics-ready datasets
    marts:
      +materialized: table
      +schema: marts
      core:
        +tags: ['marts', 'core']
        +docs:
          node_color: '#FF6B6B'  # Red for marts
      marketing:
        +tags: ['marts', 'marketing']
        +docs:
          node_color: '#FF6B6B'
      product:
        +tags: ['marts', 'product']
        +docs:
          node_color: '#FF6B6B'

# Snapshot configurations
snapshots:
  ga4_warehouse:
    +target_schema: snapshots
    +unique_key: id
    +strategy: timestamp
    +updated_at: updated_at

# Seed configurations
seeds:
  ga4_warehouse:
    +schema: seeds
    +quote_columns: true

# Test configurations
tests:
  ga4_warehouse:
    +severity: warn  # Default to warn, override for critical tests
    +store_failures: true  # Store test failures for analysis